2021-08-22 23:29:19,324 - Application.log - ERROR - file path doesnt exist
Traceback (most recent call last):
  File "Application.py", line 99, in <module>
    raise Pathdoesnotexist
Pathdoesnotexist
2021-08-22 23:32:05,384 - Application.log - INFO - number of arguments :3
2021-08-22 23:32:05,384 - Application.log - INFO - dataset one file name : Source_Dir/dataset_one2.csv
2021-08-22 23:32:05,384 - Application.log - INFO - dataset two file name : Source_Dir/dataset_two2.csv
2021-08-22 23:32:05,384 - Application.log - INFO - dataset country list : ['United Kingdom', 'Netherlands']
2021-08-22 23:32:17,274 - Application.log - ERROR - Dataset_one file doesnt exist
2021-08-22 23:32:17,274 - Application.log - ERROR - file path doesnt exist
Traceback (most recent call last):
  File "Application.py", line 94, in <module>
    raise Pathdoesnotexist
Pathdoesnotexist
2021-08-23 00:52:24,144 - Application.log - INFO - -----------Job started-----------
2021-08-23 00:52:24,144 - Application.log - INFO - number of arguments :3
2021-08-23 00:52:24,145 - Application.log - INFO - dataset one file name : Source_Dir/dataset_one.csv
2021-08-23 00:52:24,145 - Application.log - INFO - dataset two file name : Source_Dir/dataset_two.csv
2021-08-23 00:52:24,145 - Application.log - INFO - dataset country list : ['United Kingdom', 'Netherlands']
2021-08-23 00:52:30,121 - Application.log - INFO - dataset_one exists
2021-08-23 00:52:30,121 - Application.log - INFO - dataset_one exists
2021-08-23 00:52:32,621 - Application.log - INFO - Client data from created
2021-08-23 00:52:33,166 - Application.log - INFO - Client data filtered
2021-08-23 00:52:33,185 - Application.log - INFO - financial data from created
2021-08-23 00:52:33,267 - Application.log - INFO - financial data farm columns renamed
2021-08-23 00:52:36,384 - Application.log - INFO - -----------Final file created in client_data-----------------
